name: Creative
version: ${project.version}
main: pl.trollcraft.creative.Creative
api-version: 1.13
author: SkepsonSk
description: A creative server manager plugin.
depends: [PlaceholderAPI, PlotSquared, Multiverse-Core]

commands:

  teleport:
    description: A teleport command.
    aliases: [tp]
  tphere:
    description: Teleports target to the sender.
  tpa:
    description: An accepted teleport command.
  tpaccept:
    description: Accepts a teleport demand.
  tpdeny:
    description: Refuses a teleport demand.
    aliases: [tpd]
  tptoggle:
    description: Enables/Disables to demand a teleport

  rename:
    description: Changes name of an item.
    aliases: [nazwa]
  lore:
    description: Changes lore of an item.
    aliases: [opis]
  nick:
    description: Changes player name.
  jazda:
    description: Ride a mob.

  shop:
    description: Displays the shop.
    aliases: [sklep, skl, sho, shp]

  seen:
    description: See when the player was last time online.

  tails:
    description: Tails management command.
    aliases: [ogony, ogon, ogo]
  vehicles:
    description: Vehicles management command.
    aliases: [pojazdy, pojazd, poj]

  redstonesign:
    description: Creates a redstone sign.
    aliases: [rs, reds, redsign]

  gamemode:
    description: Changes a gamemode of a player.
    aliases: [gm]

  speed:
    description: Adjust your speed.
    aliases: [predkosc, ped, pred]

  event:
    description: Makes players able to create their own mini-events.
    aliases: [ev, zd, eve]

  myplot:
    description: Opens a menu allowing to control the plot.
    aliases: [mp, mypl]

  wed:
    description: Debugs world edit restrictions;

  prefixes:
    description: Opens a prefixes shop and menu.
    aliases: [prefixy, prefiksy, pref]

  colors:
    description: Changes the color the player writes with.
    aliases: [kolory, cols, kols]

  parkour:
    description: Manages parkours.

  pet:
    description: Test command.

  safety:
    description: Safety manager allowing to run safety scans and leak resolving.

  spawn:
    description: Teleports to the spawn.

  setspawn:
    description: Sets the spawn point.

  chat:
    description: Chat management command.

  broadcast:
    description: Broadcasts a message to all players online.
    aliases: [announce, bc, say]

  message:
    description: Private messaging system.
    aliases: [msg, tell]

  response:
    description: Responses to recent messages.
    aliases: [r]

  sit:
    description: Makes the player sit.
    aliases: [usiadz, siadz]

  gry:
    description: Games command.
    aliases: [games, gra, game]

  home:
    description: Home system. Teleports player to home if created.
    aliases: [dom]

  sethome:
    description: Creates new home for the player.
    aliases: [newhome]

  delhome:
    description: Deletes selected home.
    aliases: [removehome]

  warp:
    description: Teleports to the warp.

  setwarp:
    description: Creates new warp.

  delwarp:
    description: Deletes selected warp.

  openinventory:
    description: Command to open inventory of another player
    aliases: [oi]

  openenderchest:
    description: Command to open enderchest of another player
    aliases: [oe]

  adminchat:
    description: Admin chat Command
    aliases: [ac, achat]

  hat:
    description: Wear anything on your head